# Generated by Django 5.0 on 2023-12-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_code',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True, verbose_name='Verification_code'),
        ),
        migrations.AlterField(
            model_name='user',
            name='own_invite_key',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True, verbose_name='Own_invite_key'),
        ),
    ]
