# Generated by Django 5.0 on 2023-12-12 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_alien_invite_key_user_related_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='invite_key',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Invite_key'),
        ),
    ]
